### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by westnordost** [ENT8R/oneway-data-api#4]
I've read through the code and noticed a few things. I will just write everything I found in here.

- Relying on fixed column order in CSV (**minor**): https://github.com/ENT8R/oneway-data-api/blob/master/update.php#L62-L66
- id pkey necessary? (**comment**): https://github.com/ENT8R/oneway-data-api/blob/master/update.php#L18
- Unnecessary bloat: The whole `vendor` directory, the autoload stuff and the composer files would be unnecessary if the script would parse the LINESTRING itself into an array (that should be just a few LOC)
- Calling https://ent8r.lima-city.de/oneway-data-api/get.php?bbox=18,-34 yields no error, instead just an empty result
- The result here https://ent8r.lima-city.de/oneway-data-api/get.php?bbox=18,-34,19,-33 encodes the values as strings. (Or would it be better to output the data as CSV anyway?)
- Maybe rename get.php to index.php?

**Comment by westnordost** [comment]
Additionally:
- Why `ABS` in that query? Like Math.abs? That would be very wrong. Also, for the `BETWEEN` syntax, does it matter which is the lower and which is the upper bound? https://github.com/ENT8R/oneway-data-api/blob/master/get.php#L30

**Comment by exploide** [comment]
Enough for today, I will have a look tomorrow. But to give preliminary answers:

- Fixed order assumptions could be improved by consulting the first line. Will we do this @ENT8R 
- I also wondered if pkey is necessary, it is not when wayId is guaranteed to be unique. Is this the case? Then I will remove this.
- Also have this feeling about vendor directory.
- Demo site is not up to date, there should be an error
- Since I fetch data from DB, it's no longer a string but a number (demo site not up to date)
- File renaming was just done by @ENT8R the other way around. Don't know, I con't care.
- ABS (yes, like Math.abs) was just copied from @ENT8R s calculation. For the BETWEEN thing, let me look tomorrow :P

**Comment by westnordost** [comment]
> I also wondered if pkey is necessary, it is not when wayId is guaranteed to be unique. Is this the case? Then I will remove this.
wayId is not unique.

**Comment by exploide** [comment]
Ok, once #6 is merged, most points are done.

Regarding the primary key thing. Technically it's not necessary but strongly advised. Since wayId is not unique, I used this artificial id column for that purpose. Let's keep this for now. Additionally, I created a DB index on latitude and longitude, which speeds up queries that test these columns. My example query got a speed up from 0.04 s to 0.01 s. Should be fast enough for this application :D

Apart of a correctness check, the only thing left now is getting rid of geophp and composer. I leave this for @ENT8R

**Comment by ENT8R** [comment]
Did this now. There is no `vendor` directory anymore which means that there are no other external dependencies needed.
I think that we solved everything now. Is there still something open or can I close this issue?

**Comment by exploide** [comment]
I assume you checked whether the license of the copied files is compatible with this project.

Maybe it is consistent if the own `geometry_utils.php` would also live in the `geometry/` subfolder?!

The only further thing I could imagine: `update.php` is still reachable when this project gets deployed as it is. One could configure the webserver to forbid access to this file but this would require more work for the admin. Instead, and if all agree that this should be not reachable, I propose what I usually do when developing web applications: The code that belongs to the actual web application (`index.php` and `config.sample.php` here) go into their own `web/` subfolder (you can also name this `html/` or whatever). Then, the webserver can simply be pointed to `web/` as the document root, and everything else is fine. `update.php`, the `.git/` repo folder and all this meta stuff like `README.md`, `.gitignore`, `.editorconfig` etc. are out of the way for the webserver. This is something one should usually do, because making `.git/` accessible from the web can be problematic especially when this would be a closed source project.

Apart of that, I don't know what else to do. @westnordost may have a second look and maybe it would be good if you update your live instance for his testing ;)

**Comment by westnordost** [comment]
Different idea: The update.php records when was the last time the dump has been imported successfully and if it was the same day as $today, it will do nothing.

I agree with @exploide that the distance and center point calculation methods should go into the Line class.

**Comment by exploide** [comment]
Personally I like my idea more because this date recording does nothing on the "clean and secure" deployment thing (personal taste), requires more logic and a temporary file / log file, and hinders testing and development because there you want to do this multiple times a day.

But I leave this up to you both, because it's @ENT8R repository and your deployment. Do what you want :D

**Comment by ENT8R** [comment]
> I assume you checked whether the license of the copied files is compatible with this project.

Yes, the project uses GPLv2 or the BSD license

---
I like the idea @exploide proposed a little bit more. I will change this.

**Comment by ENT8R** [comment]
The files necessary for the API are now at the `/web` subfolder

**Comment by ENT8R** [comment]
True. Is done now.

**Comment by exploide** [comment]
Don't know if you plan to do something concerning points 2 and 3 from https://github.com/ENT8R/oneway-data-api/issues/4#issuecomment-381638992 but beside that...

@westnordost may feel free to start his own deployment if he likes. So I see if everything works out with this webspace provider.
