### ISSUE TITLE
mod_fcgid: read data timeout in 20 seconds

### ISSUE THREAD

**Issue by westnordost** [ENT8R/oneway-data-api#9]
I deployed it now. However, I have problems when trying to execute the `update.php`:

The log says
```
mod_fcgid: read data timeout in 20 seconds
End of script output before headers: update.php
```

Any ideas?

I do not have access on the webhost to any `conf` files.

Adding something like
```
<IfModule mod_fcgid.c>
FcgidIOTimeout 90
</IfModule>
```
to the .htaccess file does yield in an error, stating `[core:alert] .htaccess: FcgidIOTimeout not allowed here`. I read that many hosters do not allow changing the setting (this way), so I guess my hoster is the same here.

**Comment by rugk** [comment]
Sometimes you only have to kindly ask your hoster and they may change it.

**Comment by exploide** [comment]
Ok, let's see. Following comments partly interwoven with what I would write in #8.

The way you configure the cron job there to execute `update.php` looks weird to me. What does all the web stuff (mod_fcgid, .htaccess) has to do with it? Is this the only way your hoster lets you configure cron jobs? Usually you would just have a script or a line in crontab that says `php -f /path/to/update.php`. No web stuff involved, but requires php-cli to be present on the machine (it probably is?! saw that this hoster offers ssh access, so you could check). Can you execute this on command line? This would be much simpler. This also would make the change concerning `max_execution_time` obsolete.

In #8 you told something about a `/httpdocs/crons/` folder. What's the exact purpose of this folder? Is everything that's placed there executed regularly? As a simple script? Then you could place a script containing the php command there. Or maybe it works with creating a symlink there that points to `update.php`. This way you don't need to split the repository structure for deployment and `update.php` could live beside `index.php` as it is.

**Comment by westnordost** [comment]
I can configure scheduled tasks over this interface:
https://docs.plesk.com/en-US/12.5/customer-guide/scheduling-tasks.65207/

Though, the mentioned error `mod_fcgid: read data timeout in 20 seconds` comes from calling the update.php from web.

I will check about the commandline stuff and whether the tasks scheduled over that interface would use the commandline directly or call it "from the web".

**Comment by exploide** [comment]
Wonderful :) Ok, there are three types of tasks and it should definitely not be "Fetch a URL".

I don't know how "Run a PHP script" works internally, but you might give it a try. Hopefully it's running the script locally (that would be what I proposed) instead of fetching it via web (because I would assume that's the fetch URL task type).

If this won't work sufficiently, let's do this manually by using the option "Run a command". Command `php` with options `-f /path/to/update.php` should do the trick. Maybe you must fiddle with the path due to the note from the documentation. This option, however, can only work if you can invoke `php` from the commandline.

The "Run a command" option should allow us do the `.htaccess` trick I recently proposed in #8, the "Run a PHP script" option hopefully also does, but I don't know how exactly this works, while "Fetch a URL" would be undesirable for us. Then you probably end up with the problem you originally opened this issue for. (But the `.htaccess` trick could also work when properly adapted. We would need to allow web access from localhost or whatever the cron fetch is run from.)

**Comment by rugk** [comment]
> htaccess trick I recently proposed

Note some hosters do not allow users to override the config in custom htaccess files sometimes.

In any cease, however, you can very easily detect in the php code itself whether the file has been called from the command line or via web. That could be a very easy limitation.

**Comment by westnordost** [comment]
It worked! Thank you all!

**Comment by exploide** [comment]
May I ask how you finally set up the cron job? :D
